[welcome]
salutations = [
    "Hey, are you doing fine?",
    "Nice to hear from you, sir",
    "How are you feeling?",
    "Hi",
    "Time to make me work?",
    "It's been a while, it's all okay?"
]
